// Package content provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package content

// Content defines model for Content.
type Content struct {
	Body  string   `json:"body"`
	Id    string   `json:"id"`
	Tags  []string `json:"tags"`
	Title string   `json:"title"`
}

// Contents defines model for Contents.
type Contents = []Content

// ErrorMsg defines model for ErrorMsg.
type ErrorMsg struct {
	Error string `json:"error"`
}

// PatchContent defines model for PatchContent.
type PatchContent struct {
	Body  string   `json:"body"`
	Tags  []string `json:"tags"`
	Title string   `json:"title"`
}

// PostContent defines model for PostContent.
type PostContent struct {
	Body  string   `json:"body"`
	Tags  []string `json:"tags"`
	Title string   `json:"title"`
}

// ContentId defines model for contentId.
type ContentId = string

// GetContents defines model for GetContents.
type GetContents = Contents

// PatchAdminContentContentIdJSONRequestBody defines body for PatchAdminContentContentId for application/json ContentType.
type PatchAdminContentContentIdJSONRequestBody = PatchContent

// PostAdminContentsJSONRequestBody defines body for PostAdminContents for application/json ContentType.
type PostAdminContentsJSONRequestBody = PostContent
