// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package public

// Content defines model for Content.
type Content struct {
	Body  string   `json:"body"`
	Id    string   `json:"id"`
	Tags  []string `json:"tags"`
	Title string   `json:"title"`
}

// Contents defines model for Contents.
type Contents = []Content

// ContentId defines model for contentId.
type ContentId = string

// ErrorMsg defines model for ErrorMsg.
type ErrorMsg struct {
	Error string `json:"error"`
}

// GetContent defines model for GetContent.
type GetContent = Content

// GetContents defines model for GetContents.
type GetContents = Contents
