// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package public

// Article defines model for Article.
type Article struct {
	Author      string   `json:"author"`
	Body        string   `json:"body"`
	Description string   `json:"description"`
	Id          int      `json:"id"`
	Tags        []string `json:"tags"`
	Title       string   `json:"title"`
}

// Articles defines model for Articles.
type Articles = []Article

// ArticleId defines model for articleId.
type ArticleId = int

// ErrorMsg defines model for ErrorMsg.
type ErrorMsg struct {
	Error string `json:"error"`
}

// GetContent defines model for GetContent.
type GetContent struct {
	Data Article `json:"data"`
}

// GetContents defines model for GetContents.
type GetContents struct {
	Data Articles `json:"data"`
}
