// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package public

import (
	"time"
)

// Article defines model for Article.
type Article struct {
	Author      string    `json:"author"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"createdAt"`
	Description string    `json:"description"`
	Id          int       `json:"id"`
	Tags        []string  `json:"tags"`
	Title       string    `json:"title"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// Articles defines model for Articles.
type Articles = []Article

// ArticleId defines model for articleId.
type ArticleId = int

// ErrorMsg defines model for ErrorMsg.
type ErrorMsg struct {
	Error string `json:"error"`
}

// GetArticle defines model for GetArticle.
type GetArticle struct {
	Data Article `json:"data"`
}

// GetArticles defines model for GetArticles.
type GetArticles struct {
	Data Articles `json:"data"`
}
