openapi: 3.0.0
info:
  title: API
  version: 0.0.1
servers:
  - url: '{env}/api/v1'
    variables:
      env:
        default: http://localhost:8080
        enum:
          - http://localhost:8080
paths:
  /admin/articles:
    get:
      operationId: getArticles
      responses:
        '200': {$ref: '#/components/responses/GetArticles'}
        '500': {$ref: '#/components/responses/ErrorMsg'}
    post:
      summary: Create new article
      requestBody: {$ref: '#/components/requestBodies/PostArticle'}
      responses:
        '200': {description: Article created}
        '400': {$ref: '#/components/responses/ErrorMsg'}
        '500': {$ref: '#/components/responses/ErrorMsg'}
    delete:
      summary: Delete all article
      responses:
        '200': {description: All article deleted}
        '500': {$ref: '#/components/responses/ErrorMsg'}
  /admin/article/{articleId}:
    patch:
      summary: Update article
      parameters:
        - $ref: '#/components/parameters/articleId'
      requestBody: {$ref: '#/components/requestBodies/PatchArticle'}
      responses:
        '200': {description: Article updated}
        '400':
          $ref: '#/components/responses/ErrorMsg'
        '404':
          $ref: '#/components/responses/ErrorMsg'
        '500': {$ref: '#/components/responses/ErrorMsg'}
components:
  parameters:
    userIds:
      name: userIds
      in: query
      required: true
      schema:
        type: array
        items:
          type: string
    userId:
      name: userId
      in: path
      required: true
      schema:
        type: string
    articleId:
      name: articleId
      in: path
      required: true
      schema:
        type: string
  requestBodies:
    PostArticle:
      required: true
      content:
        application/json:
          schema: {$ref: '#/components/schemas/PostArticle'}
    PatchArticle:
      required: true
      content:
        application/json:
          schema: {$ref: '#/components/schemas/PatchArticle'}
  responses:
    ErrorMsg:
      description: Error message
      content:
        application/json:
          schema: {$ref: '#/components/schemas/ErrorMsg'}
    GetArticles:
      description: List of articles
      content:
        application/json:
          schema: {$ref: '#/components/schemas/Articles'}
  schemas:
    ErrorMsg:
      type: object
      properties:
        error: {type: string}
      required: [error]
    Article:
      type: object
      properties:
        id: {type: number, format: int64, x-go-type: int}
        title: {type: string}
        body: {type: string}
        tags: {type: array, items: {type: string}}
      required: [id, title, body, tags]
    Articles:
      type: array
      items: {$ref: '#/components/schemas/Article'}
      required: [nick, email, userType]
    PostArticle:
      type: object
      properties:
        title: {type: string}
        body: {type: string}
        tags: {type: array, items: {type: string}}
      required: [title, body, tags]
    PatchArticle:
      type: object
      properties:
        title: {type: string}
        body: {type: string}
        tags: {type: array, items: {type: string}}
      required: [title, body, tags]
  securitySchemes: {}
security: []
