name: Build docker image and push to registry

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'

jobs:
    docker:
        runs-on: ubuntu-latest
        environment: production
        steps:
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              push: true
              tags: armatorix/gopress:latest, armatorix/gopress:${{ github.ref_name }}